name: Handle PDF Upload
on:
  issues:
    types: [opened]

jobs:
  process-pdf:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.title, 'PDF Upload:')
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup GitHub CLI
        run: |
          gh auth login --with-token <<< "${{ secrets.PAT_TOKEN }}"
      
      - name: Process PDF
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          # Get issue number and create papers directory
          ISSUE_NUMBER="${{ github.event.issue.number }}"
          mkdir -p papers
          
          # Add comment to issue
          gh issue comment "$ISSUE_NUMBER" --body "Processing PDF upload..."
          
          # Get paper ID from issue body
          PAPER_ID=$(gh issue view "$ISSUE_NUMBER" --json body -q '.body' | grep -o 'PaperID: .*' | cut -d' ' -f2)
          
          # Create empty PDF file to track
          touch "papers/$PAPER_ID.pdf"
          
          # Commit and push the changes
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add "papers/$PAPER_ID.pdf"
          git commit -m "Initialize PDF file for issue #$ISSUE_NUMBER"
          git push 