name: Handle PDF Upload
on:
  issues:
    types: [opened]

jobs:
  process-pdf:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.title, 'PDF Upload:')
    steps:
      - uses: actions/checkout@v2
      
      - name: Process PDF
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          # Get issue number and create papers directory
          ISSUE_NUMBER="${{ github.event.issue.number }}"
          mkdir -p papers
          
          # Get issue content
          ISSUE_BODY=$(gh issue view "$ISSUE_NUMBER" --json body -q '.body')
          
          # Extract paper ID and content
          PAPER_ID=$(echo "$ISSUE_BODY" | grep -o 'PaperID: .*' | cut -d' ' -f2)
          PDF_CONTENT=$(echo "$ISSUE_BODY" | grep -o 'Content: .*' | cut -d' ' -f2-)
          
          # Save PDF
          echo "$PDF_CONTENT" | base64 -d > "papers/$PAPER_ID.pdf"
          
          # Commit and push
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add "papers/$PAPER_ID.pdf"
          git commit -m "Add PDF from issue #$ISSUE_NUMBER"
          git push 