name: Handle PDF Upload
on:
  issues:
    types: [opened]

jobs:
  process-pdf:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.title, 'PDF Upload:')
    steps:
      - uses: actions/checkout@v2
      - name: Process PDF
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          # Process the uploaded PDF
          ISSUE_NUMBER="${{ github.event.issue.number }}"
          echo "Processing PDF from issue #$ISSUE_NUMBER"
          
          # Create papers directory if it doesn't exist
          mkdir -p papers
          
          # Add comment to issue about processing status
          gh issue comment "$ISSUE_NUMBER" --body "Processing PDF upload..."
          
          # Commit and push the changes
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add papers/
          git commit -m "Add PDF from issue #$ISSUE_NUMBER" || echo "No changes to commit"
          git push 