name: Handle PDF Upload
on:
  issues:
    types: [opened]

jobs:
  process-pdf:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.title, 'PDF Upload:')
    steps:
      - uses: actions/checkout@v2
      - name: Process PDF
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          # Get issue body
          ISSUE_NUMBER="${{ github.event.issue.number }}"
          ISSUE_BODY=$(gh api /repos/${{ github.repository }}/issues/$ISSUE_NUMBER --jq .body)
          
          # Extract base64 data and metadata
          PDF_DATA=$(echo "$ISSUE_BODY" | grep -o 'Data:.*' | cut -d$'\n' -f1 | sed 's/Data://')
          PAPER_ID=$(echo "$ISSUE_BODY" | grep -o 'PaperID:.*' | cut -d$'\n' -f1 | sed 's/PaperID://')
          
          # Create papers directory
          mkdir -p papers
          
          # Save PDF
          echo "$PDF_DATA" | base64 -d > "papers/$PAPER_ID.pdf"
          
          # Commit and push
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add papers/
          git commit -m "Add PDF from issue #$ISSUE_NUMBER"
          git push 